### PR TITLE
Install python3-boto3

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR installs the `python3-boto3` package.

## 💭 Motivation and context ##

As part of the work for https://github.com/cisagov/cool-assessment-terraform/issues/115, we need to run a cloud-init script to fetch a certificate from our S3 bucket.  In order for that script to work, `boto3` must be installed.

## 🧪 Testing ##

I tested this by creating a new pre-release AMI in Staging with this change and verified that the [`install-certificates.py` cloud-init script](https://github.com/cisagov/cool-assessment-terraform/blob/develop/cloud-init/install-certificates.py) could be run successfully.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.
* [x] Finalize version with `bump_version.sh finalize`

## ✅ Post-Merge Checklist ##
* [ ] Create Production release
* [ ] Apply `terraform-post-packer` to make new AMI available to all COOL accounts

### CODE REVIEW

**Comment by jsf9k** [comment]
@dav3r, when you tested this did you have to modify the instance to allow IMDSv1?

**Comment by dav3r** [comment]
> > @dav3r, when you tested this did you have to modify the instance to allow IMDSv1? [This](https://packages.debian.org/buster-backports/python3-botocore) should make that unnecessary, although you have to install like so:
> > ```yaml
> > - name: Install python3-boto3
> >   ansible.builtin.apt:
> >     default_release: buster-backports
> >     name: 
> >       - python3-boto3
> >       - python3-botocore
> > ```
> 
> Ah, nevermind. I forgot that this one is already on Bullseye.

Yes, with Bullseye, this worked the way I currently have it.

**Review by mcdonnnj — APPROVED** [review]
LGTM ✅

**Review by jsf9k — APPROVED** [review]

**Review by felddy — APPROVED** [review]
Strong. 💪 
Tree. 🌴

**Pull request merged**
